# Defina as variáveis diretamente no Vagrantfile
CONTROL_PLANE_MEMORY = 4096 # 4GB RAM
CONTROL_PLANE_CPUS = 4
WORKER_MEMORY = 2048 # 2GB RAM por worker
WORKER_CPUS = 2
NETWORK_PREFIX = "192.168.56"
CONTROL_PLANE_IP = "#{NETWORK_PREFIX}.10"
WORKER_IP_START = 11

Vagrant.configure("2") do |config|
    # Configuração comum para todas as VMs
    config.vm.provision "file", source: "configs/.", destination: "/home/vagrant/"
    config.vm.provision "shell", path: "configs/aditional-install.sh"

    # Configuração do Control Plane
    config.vm.define "control-plane", primary: true do |control|
        control.vm.box = "ubuntu-24.04-updated"
        control.vm.hostname = "control-plane"
        control.vm.network "private_network", ip: CONTROL_PLANE_IP, netmask: "255.255.255.0"
        
        control.vm.provider "virtualbox" do |vb|
            vb.memory = CONTROL_PLANE_MEMORY
            vb.cpus = CONTROL_PLANE_CPUS
        end

        control.vm.provision "shell", path: "configs/conf_controlplane.sh", env: {
            "CONTROL_PLANE_IP" => CONTROL_PLANE_IP
        }
    end

    # Configuração dos Workers
    (1..4).each do |i|
        config.vm.define "worker-#{i}" do |worker|
            worker.vm.box = "ubuntu-24.04-updated"
            worker.vm.hostname = "worker-#{i}"
            worker.vm.network "private_network", ip: "#{NETWORK_PREFIX}.#{WORKER_IP_START + i - 1}", netmask: "255.255.255.0"
            
            worker.vm.provider "virtualbox" do |vb|
                vb.memory = WORKER_MEMORY
                vb.cpus = WORKER_CPUS
            end

            worker.vm.provision "shell", path: "configs/conf_workers.sh"
        end
    end
end
